baseURL = 'http://tubaozi.top/'
languageCode = 'zh-cn'
title = 'My New Hugo Site'
theme='diary'
DefaultContentLanguage = "zh"

[[menu.main]]
url = "/posts"
name = "Categories"
weight = 3

[[menu.main]]
url = "/aa"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1